# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-01-13 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import signbank.video.models


class Migration(migrations.Migration):

    replaces = [('video', '0001_initial'), ('video', '0002_auto_20161013_1049'), ('video', '0003_glossvideo_dataset'), ('video', '0004_auto_20161016_1842'), ('video', '0005_glossvideo_posterfile'), ('video', '0006_glossvideo_title'), ('video', '0007_auto_20161201_0821'), ('video', '0008_auto_20170407_1315'), ('video', '0009_auto_20170509_1929'), ('video', '0010_auto_20170511_1748'), ('video', '0011_auto_20170925_1530'), ('video', '0012_delete_video'), ('video', '0013_auto_20180325_1358'), ('video', '0014_glossvideo_is_public')]

    initial = True

    dependencies = [
        ('dictionary', '0020_auto_20160913_1404'),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(help_text='Video file.', storage=signbank.video.models.GlossVideoStorage(), upload_to='', verbose_name='Video file')),
                ('version', models.IntegerField(default=0, help_text="A number that represents the order of the Glossvideo's in a gloss page. Smaller number means higher priority.", verbose_name='Version')),
                ('gloss', models.ForeignKey(help_text='The gloss this GlossVideo is related to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Gloss', verbose_name='Gloss')),
                ('dataset', models.ForeignKey(help_text='Dataset of a GlossVideo, derived from gloss (if any) or chosen when video was uploaded.', null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Dataset', verbose_name='Glossvideo dataset')),
                ('posterfile', models.FileField(blank=True, default='', help_text='Still image representation of the video.', storage=signbank.video.models.GlossVideoStorage(), upload_to='posters', verbose_name='Poster file')),
                ('title', models.CharField(blank=True, help_text='Descriptive name of the video.', max_length=100, verbose_name='Title')),
                ('is_public', models.BooleanField(default=True, help_text='Is this video is public or private?', verbose_name='Public')),
            ],
            options={
                'ordering': ['version'],
                'verbose_name': 'Gloss video',
                'verbose_name_plural': 'Gloss videos',
            },
        ),
    ]
