# Generated by Django 2.2.9 on 2020-01-25 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_squashed_0014_glossvideo_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossvideo',
            name='dataset',
            field=models.ForeignKey(help_text='Dataset of a GlossVideo, derived from gloss (if any) or chosen when video was uploaded.', null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Dataset', verbose_name='Glossvideo dataset'),
        ),
    ]
