# Generated by Django 2.2.11 on 2022-05-05 23:48

from django.db import migrations, models
import signbank.video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20200125_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossvideo',
            name='posterfile',
            field=models.FileField(blank=True, default='', help_text='Still image representation of the video.', storage=signbank.video.models.GlossVideoDynamicStorage(), upload_to='posters', verbose_name='Poster file'),
        ),
        migrations.AlterField(
            model_name='glossvideo',
            name='videofile',
            field=models.FileField(help_text='Video file.', storage=signbank.video.models.GlossVideoDynamicStorage(), upload_to='', verbose_name='Video file'),
        ),
    ]
