# Generated by Django 2.2.11 on 2022-05-18 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20220506_1148')
    ]

    operations = [
        migrations.AddField(
            model_name='glossvideo',
            name='video_type',
            field=models.ForeignKey(help_text='The type of video this is for on the gloss', limit_choices_to={
                                    'field': 'video_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Video type'),
        ),
    ]
