# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_glossvideo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossvideo',
            name='dataset',
            field=models.ForeignKey(help_text='Dataset for a glossvideo', null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Dataset', verbose_name='Glossvideo dataset'),
        ),
    ]
