# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20170407_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossvideo',
            options={'ordering': ['version']},
        ),
    ]
