# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_auto_20170925_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
