# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import signbank.video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossvideo',
            name='posterfile',
            field=models.FileField(blank=True, default='', help_text='Still image representation of the video.', storage=signbank.video.models.GlossVideoStorage(), upload_to='posters', verbose_name='Poster file'),
        ),
        migrations.AlterField(
            model_name='glossvideo',
            name='videofile',
            field=models.FileField(help_text='Video file.', storage=signbank.video.models.GlossVideoStorage(), upload_to='', verbose_name='Video file'),
        ),
    ]
