# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-22 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_auto_20180325_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossvideo',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Is this video is public or private?', verbose_name='Public'),
        ),
    ]
