# Generated by Django 2.2.9 on 2020-01-25 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_squashed_0047_auto_20180629_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['id'], 'permissions': (('access_dataset', 'Access dataset'),), 'verbose_name': 'Lexicon', 'verbose_name_plural': 'Lexicons'},
        ),
        migrations.AlterField(
            model_name='dataset',
            name='signlanguage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.SignLanguage', verbose_name='Sign language'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='absolute_orientation_fingers',
            field=models.ForeignKey(blank=True, db_column='absolute_orientation_fingers', limit_choices_to={'field': 'absolute_orientation_fingers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absolute_orientation_fingers', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Absolute Orientation: Fingers'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='absolute_orientation_palm',
            field=models.ForeignKey(blank=True, db_column='absolute_orientation_palm', limit_choices_to={'field': 'absolute_orientation_palm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absolute_orientation_palm', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Absolute Orientation: Palm'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='contact_type',
            field=models.ForeignKey(blank=True, db_column='contact_type', limit_choices_to={'field': 'contact_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_type', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Contact Type'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='dataset',
            field=models.ForeignKey(help_text='Dataset a gloss is part of', on_delete=django.db.models.deletion.PROTECT, to='dictionary.Dataset', verbose_name='Glosses dataset'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='handedness',
            field=models.ForeignKey(blank=True, db_column='handedness', limit_choices_to={'field': 'handedness'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handedness', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Handedness'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='handshape_change',
            field=models.ForeignKey(blank=True, db_column='handshape_change', limit_choices_to={'field': 'handshape_change'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handshape_change', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Handshape Change'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='location',
            field=models.ForeignKey(blank=True, db_column='location', limit_choices_to={'field': 'location'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='movement_direction',
            field=models.ForeignKey(blank=True, db_column='movement_direction', limit_choices_to={'field': 'movement_direction'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_direction', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Movement Direction'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='movement_manner',
            field=models.ForeignKey(blank=True, db_column='movement_manner', limit_choices_to={'field': 'movement_manner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_manner', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Movement Manner'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='movement_shape',
            field=models.ForeignKey(blank=True, db_column='movement_shape', limit_choices_to={'field': 'movement_shape'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_shape', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Movement Shape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='named_entity',
            field=models.ForeignKey(blank=True, db_column='named_entity', limit_choices_to={'field': 'named_entity'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='named_entity', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Named Entity'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='orientation_change',
            field=models.ForeignKey(blank=True, db_column='orientation_change', limit_choices_to={'field': 'orientation_change'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientation_change', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Orientation Change'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='relation_between_articulators',
            field=models.ForeignKey(blank=True, db_column='relation_between_articulators', limit_choices_to={'field': 'relation_between_articulators'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_between_articulators', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Relation Between Articulators'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='relative_orientation_location',
            field=models.ForeignKey(blank=True, db_column='relative_orientation_location', limit_choices_to={'field': 'relative_orientation_location'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relative_orientation_location', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Relative Orientation: Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='relative_orientation_movement',
            field=models.ForeignKey(blank=True, db_column='relative_orientation_movement', limit_choices_to={'field': 'relative_orientation_movement'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relative_orientation_movement', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Relative Orientation: Movement'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='semantic_field',
            field=models.ForeignKey(blank=True, db_column='semantic_field', limit_choices_to={'field': 'semantic_field'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semantic_field', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Semantic Field'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='strong_handshape',
            field=models.ForeignKey(blank=True, db_column='strong_handshape', limit_choices_to={'field': 'strong_handshape'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strong_handshape', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Strong Hand'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='weak_handshape',
            field=models.ForeignKey(blank=True, db_column='weak_handshape', limit_choices_to={'field': 'weak_handshape'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weak_handshape', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Weak Hand'),
        ),
        migrations.AlterField(
            model_name='morphologydefinition',
            name='role',
            field=models.ForeignKey(blank=True, db_column='MorphologyType', limit_choices_to={'field': 'MorphologyType'}, on_delete=django.db.models.deletion.CASCADE, to='dictionary.FieldChoice', to_field='machine_value'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='role',
            field=models.ForeignKey(blank=True, db_column='MorphologyType', limit_choices_to={'field': 'MorphologyType'}, on_delete=django.db.models.deletion.CASCADE, to='dictionary.FieldChoice', to_field='machine_value'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.Keyword', verbose_name='Keyword'),
        ),
    ]
