# Generated by Django 2.2.11 on 2021-08-28 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_gloss_idgloss_mi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gloss',
            name='idgloss_mi',
        ),
    ]
