# Generated by Django 2.2.11 on 2021-08-28 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_remove_gloss_idgloss_mi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gloss',
            old_name='idgloss_en',
            new_name='idgloss_mi',
        ),
    ]
