# Generated by Django 3.2.15 on 2023-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20220108_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='copyright_sv',
            field=models.TextField(null=True, verbose_name='Copyright'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='description_sv',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='public_name_sv',
            field=models.CharField(max_length=60, null=True, verbose_name='Public name'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_sv',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='signlanguage',
            name='name_sv',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
