# Generated by Django 2.2.11 on 2021-08-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_rename_gloss_idgloss_en_mi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='idgloss_mi',
            field=models.CharField(blank=True, help_text='This is the Māori name for the Gloss', max_length=60, verbose_name='Gloss in Māori'),
        ),
    ]
