# Generated by Django 3.2.18 on 2024-02-17 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20230531_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossurl',
            name='sign_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.signlanguage', verbose_name='Sign language'),
        ),
    ]
