# Generated by Django 3.2.18 on 2024-09-01 10:40

from django.db import migrations, models

def populate_public_name(apps, schema_editor):
    SignLanguage = apps.get_model('dictionary', 'SignLanguage')
    for signlanguage in SignLanguage.objects.all():
        signlanguage.public_name = signlanguage.name
        signlanguage.public_name_en = signlanguage.name_en
        signlanguage.public_name_fi = signlanguage.name_fi
        signlanguage.public_name_sv = signlanguage.name_sv
        signlanguage.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_dataset_show_urls_in_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='signlanguage',
            name='public_name',
            field=models.CharField(default='', help_text='Name to use in public interface', max_length=100),
        ),
        migrations.AddField(
            model_name='signlanguage',
            name='public_name_en',
            field=models.CharField(default='', help_text='Name to use in public interface', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signlanguage',
            name='public_name_fi',
            field=models.CharField(default='', help_text='Name to use in public interface', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signlanguage',
            name='public_name_sv',
            field=models.CharField(default='', help_text='Name to use in public interface', max_length=100, null=True),
        ),
        migrations.RunPython(populate_public_name, reverse_code=migrations.RunPython.noop)
    ]
