# Generated by Django 2.2.11 on 2022-02-15 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_auto_20220211_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='signer',
            field=models.ForeignKey(blank=True, help_text='Signer for the Gloss', null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Signer', verbose_name='Signer'),
        ),
        migrations.AlterField(
            model_name='glosstranslations',
            name='translations_minor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glosstranslations',
            name='translations_secondary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
