# Generated by Django 2.2.11 on 2022-05-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_auto_20220215_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='filmbatch',
            field=models.CharField(blank=True, help_text='Which batch of recordings the video is from', max_length=150, null=True),
        ),
    ]
