# Generated by Django 2.2.11 on 2022-05-11 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_auto_20220509_1618'),
        ('dictionary', '0011_gloss_filmbatch'),
    ]

    operations = [
    ]
