# Generated by Django 2.2.11 on 2022-05-12 02:49

from django.db import migrations


class Migration(migrations.Migration):
    # Just under 8,000 signs exist in the old NZSL management tool, Freelex.
    # Restart sequencing at 8000 so that new signs will have an ID that will
    # not conflict with Freelex IDs.
    SIGN_NUMBER_START_VALUE = 8000

    dependencies = [
        ('dictionary', '0012_merge_20220511_1350'),
    ]

    operations = [
        migrations.RunSQL("ALTER SEQUENCE dictionary_gloss_id_seq RESTART WITH {};".format(
            SIGN_NUMBER_START_VALUE))
    ]
