# Generated by Django 2.2.11 on 2022-05-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_auto_20220512_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Sign number'),
        ),
    ]
