# Generated by Django 2.2.11 on 2022-05-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_auto_20220512_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='videoexample1',
            field=models.CharField(blank=True, help_text='Glossing for video example 1',
                                   max_length=255, null=True, verbose_name='Example video 1 glossing'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='videoexample1_translation',
            field=models.CharField(blank=True, help_text='English translation for video example 1',
                                   max_length=255, null=True, verbose_name='Example video 1 English translation'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='videoexample2',
            field=models.CharField(blank=True, help_text='Glossing for video example 2',
                                   max_length=255, null=True, verbose_name='Example video 2 glossing'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='videoexample2_translation',
            field=models.CharField(blank=True, help_text='English translation for video example 2',
                                   max_length=255, null=True, verbose_name='Example video 2 English translation'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='videoexample3',
            field=models.CharField(blank=True, help_text='Glossing for video example 3',
                                   max_length=255, null=True, verbose_name='Example video 3 glossing'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='videoexample3_translation',
            field=models.CharField(blank=True, help_text='English translation for video example 3',
                                   max_length=255, null=True, verbose_name='Example video 3 English translation'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='videoexample4',
            field=models.CharField(blank=True, help_text='Glossing for video example 4',
                                   max_length=255, null=True, verbose_name='Example video 4 glossing'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='videoexample4_translation',
            field=models.CharField(blank=True, help_text='English translation for video example 4',
                                   max_length=255, null=True, verbose_name='Example video 4 English translation'),
        ),
    ]
