# Generated by Django 2.2.11 on 2022-05-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_auto_20220519_1725'),
        ('dictionary', '0014_auto_20220524_1157'),
    ]

    operations = [
    ]
