# Generated by Django 2.2.11 on 2022-06-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_auto_20220524_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': 'Written language', 'verbose_name_plural': 'Written languages'},
        ),
        migrations.AddField(
            model_name='gloss',
            name='number_incorporated',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Sign number'),
        ),
    ]
