# Generated by Django 2.2.11 on 2022-06-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_auto_20220524_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='wordclasses',
            field=models.ManyToManyField(limit_choices_to={
                                         'field': 'wordclass'}, to='dictionary.FieldChoice', verbose_name='Wordclasses'),
        ),
    ]
