# Generated by Django 2.2.11 on 2022-05-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_auto_20220524_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': 'Written language', 'verbose_name_plural': 'Written languages'},
        ),
        migrations.AddField(
            model_name='gloss',
            name='inflection1',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Can the sign have a temporal inflection?’', verbose_name='Inflection: Temporal'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='inflection2',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Can the sign be inflected for manner and degree?', verbose_name='Inflection: Manner and Degree'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='inflection3',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Can the sign have a plural inflection?', verbose_name='Inflection: Pluralisation'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Sign number'),
        ),
    ]
