# Generated by Django 2.2.11 on 2022-05-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_auto_20220524_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': 'Written language', 'verbose_name_plural': 'Written languages'},
        ),
        migrations.AddField(
            model_name='gloss',
            name='concise',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Was this gloss included in print 2002 Concise Dictionary of NZSL?', verbose_name='Concise'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Sign number'),
        ),
    ]
