# Generated by Django 2.2.11 on 2022-06-01 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0015_auto_20220531_1805'),
        ('dictionary', '0015_auto_20220601_1554'),
    ]

    operations = [
    ]
