# Generated by Django 2.2.11 on 2022-06-02 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0015_auto_20220531_1307'),
        ('dictionary', '0015_auto_20220531_1805'),
        ('dictionary', '0015_auto_20220601_1343'),
    ]

    operations = [
    ]
