# Generated by Django 2.2.11 on 2022-05-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0015_merge_20220525_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': 'Written language', 'verbose_name_plural': 'Written languages'},
        ),
        migrations.AddField(
            model_name='gloss',
            name='fingerspelling',
            field=models.BooleanField(default=False),
        ),
    ]
