# Generated by Django 2.2.11 on 2022-05-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0016_auto_20220601_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='fingerspelling',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
