# Generated by Django 2.2.11 on 2022-06-01 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0017_auto_20220601_1151'),
        ('dictionary', '0015_auto_20220601_1343'),
        ('dictionary', '0016_merge_20220601_1701'),
    ]

    operations = [
    ]
