# Generated by Django 2.2.11 on 2022-06-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0018_merge_20220602_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='fingerspelling',
            field=models.BooleanField(default=False, help_text='Does the sign contain fingerspelling?', verbose_name='Fingerspelling'),
        ),
    ]
