# Generated by Django 2.2.11 on 2022-06-02 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0016_merge_20220602_1419'),
        ('dictionary', '0019_auto_20220602_1437'),
    ]

    operations = [
    ]
