# Generated by Django 2.2.11 on 2022-06-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0020_merge_20220602_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='directional',
            field=models.BooleanField(default=False),
        ),
    ]
