# Generated by Django 2.2.11 on 2022-06-07 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0021_auto_20220606_1548'),
        ('dictionary', '0021_auto_20220606_1329'),
    ]

    operations = [
    ]
