# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    def set_defaults(apps, schema_editor):
        Language = apps.get_model('dictionary', 'Language')
        for lang in Language.objects.all().iterator():
            lang.name_en = lang.name
            lang.save()

    dependencies = [
        ('dictionary', '0022_auto_20161201_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RunPython(set_defaults), # Set field 'name_en' = 'name'
        migrations.AddField(
            model_name='language',
            name='name_fi',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
