# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0023_auto_20170310_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translations', models.CharField(blank=True, max_length=255)),
                ('gloss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Gloss')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Language')),
            ],
        ),
    ]
