# Generated by Django 2.2.11 on 2022-06-07 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0023_merge_20220607_1419'),
        ('dictionary', '0021_auto_20220606_1700'),
    ]

    operations = [
    ]
