# Generated by Django 2.2.11 on 2022-06-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0024_merge_20220607_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='directional',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Directional'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='locatable',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Locatable'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='number_incorporated',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Number incorporated'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='one_or_two_hand',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='One or two hands'),
        ),
    ]
