# Generated by Django 2.2.11 on 2022-06-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0025_auto_20220607_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='fingerspelling',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Does the sign contain fingerspelling?', verbose_name='Fingerspelling'),
        ),
    ]
