# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0025_auto_20170313_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'permissions': (('view_dataset', 'View dataset'),)},
        ),
    ]
