# Generated by Django 2.2.11 on 2022-06-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0026_auto_20220607_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='one_or_two_hand',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='One or two handed'),
        ),
    ]
