# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0026_auto_20170511_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossrelation_source', to='dictionary.Gloss')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossrelation_target', to='dictionary.Gloss')),
            ],
            options={
                'ordering': ['source'],
            },
        ),
    ]
