# Generated by Django 2.2.11 on 2022-06-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dictionary', '0026_auto_20220607_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='wordclasses',
            field=models.ManyToManyField(limit_choices_to={
                                         'field': 'wordclass'}, related_name='wordclass_glosses', to='dictionary.FieldChoice', verbose_name='Wordclasses'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='usage',
            field=models.ManyToManyField(limit_choices_to={
                                         'field': 'usage'}, related_name='usage_glosses', to='dictionary.FieldChoice', verbose_name='Usage'),
        ),
    ]
