# Generated by Django 2.2.11 on 2022-06-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0027_auto_20220608_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='variant_no',
            field=models.TextField(blank=True, null=True, verbose_name='Variant Number'),
        ),
    ]
