# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0027_glossrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('gloss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Gloss')),
            ],
        ),
    ]
