# Generated by Django 2.2.11 on 2022-06-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0027_auto_20220608_0859'),
        ('dictionary', '0027_auto_20220608_1206'),
    ]

    operations = [
    ]
