# Generated by Django 2.2.11 on 2022-06-09 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0027_auto_20220608_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='age_variation',
            field=models.ForeignKey(blank=True, db_column='age_variation', limit_choices_to={'field': 'age_variation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='age_variation', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Age variation'),
        ),
    ]
