# Generated by Django 2.2.11 on 2022-06-09 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0028_merge_20220608_1532'),
        ('dictionary', '0028_gloss_variant_no'),
    ]

    operations = [
    ]
