# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0028_glossurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glosstranslations',
            name='translations',
            field=models.TextField(blank=True),
        ),
    ]
