# Generated by Django 2.2.11 on 2022-06-09 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0028_gloss_age_variation'),
        ('dictionary', '0029_merge_20220609_1245'),
    ]

    operations = [
    ]
