# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0029_auto_20170626_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='annotation_comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
    ]
