# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0030_auto_20170810_1248'),
    ]

    operations = [
        migrations.RenameField('gloss', 'annotation_comments', 'notes'),
        migrations.AlterField(
            model_name='gloss',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
