# Generated by Django 2.2.11 on 2022-06-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0030_merge_20220610_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gloss',
            name='semantic_field',
        ),
        migrations.AddField(
            model_name='gloss',
            name='semantic_field',
            field=models.ManyToManyField(limit_choices_to={'field': 'semantic_field'}, related_name='semantic_field', to='dictionary.FieldChoice', verbose_name='Semantic fields'),
        ),
    ]
