# Generated by Django 3.2.13 on 2022-06-22 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0031_auto_20220621_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signer',
        ),
    ]
