# Generated by Django 3.2.13 on 2022-06-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0031_auto_20220615_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='semantic_field',
            field=models.ManyToManyField(blank=True, limit_choices_to={'field': 'semantic_field'}, related_name='semantic_field', to='dictionary.FieldChoice', verbose_name='Semantic Fields'),
        ),
    ]
