# Generated by Django 2.2.11 on 2022-06-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0031_gloss_assigned_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='usage',
            field=models.ManyToManyField(blank=True, limit_choices_to={'field': 'usage'}, related_name='usage_glosses', to='dictionary.FieldChoice', verbose_name='Usage'),
        ),
    ]
