# Generated by Django 3.2.13 on 2022-06-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0032_alter_gloss_semantic_field'),
        ('dictionary', '0032_auto_20220621_1057'),
        ('dictionary', '0032_delete_signer'),
    ]

    operations = [
    ]
