# Generated by Django 3.2.13 on 2022-06-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0033_merge_20220622_1611'),
        ('dictionary', '0033_merge_20220622_1713'),
    ]

    operations = [
    ]
