# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0033_allowedtags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedtags',
            options={'verbose_name': 'Allowed tags', 'verbose_name_plural': 'Allowed tags'},
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={'permissions': (('view_dataset', 'View dataset'),), 'verbose_name': 'Lexicon', 'verbose_name_plural': 'Lexicons'},
        ),
        migrations.AlterModelOptions(
            name='definition',
            options={'ordering': ['gloss', 'role', 'count'], 'verbose_name': 'Definition', 'verbose_name_plural': 'Definitions'},
        ),
        migrations.AlterModelOptions(
            name='dialect',
            options={'ordering': ['language', 'name'], 'verbose_name': 'Dialect', 'verbose_name_plural': 'Dialects'},
        ),
        migrations.AlterModelOptions(
            name='fieldchoice',
            options={'ordering': ['field', 'machine_value'], 'verbose_name': 'Field choice', 'verbose_name_plural': 'Field choices'},
        ),
        migrations.AlterModelOptions(
            name='gloss',
            options={'ordering': ['idgloss'], 'permissions': (('update_video', 'Can Update Video'), ('search_gloss', 'Can Search/View Full Gloss Details'), ('export_csv', 'Can export sign details as CSV'), ('import_csv', 'Can import glosses from a CSV file'), ('can_publish', 'Can publish signs and definitions'), ('view_advanced_properties', 'Include all properties in sign detail view'), ('publish_gloss', 'Can publish and unpublish Glosses')), 'verbose_name': 'Gloss', 'verbose_name_plural': 'Glosses'},
        ),
        migrations.AlterModelOptions(
            name='glossrelation',
            options={'ordering': ['source'], 'verbose_name': 'Gloss relation', 'verbose_name_plural': 'Gloss relations'},
        ),
        migrations.AlterModelOptions(
            name='glosstranslations',
            options={'verbose_name': 'Gloss translation field', 'verbose_name_plural': 'Gloss translation fields'},
        ),
        migrations.AlterModelOptions(
            name='glossurl',
            options={'verbose_name': 'Gloss URL', 'verbose_name_plural': 'Gloss URLs'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['text'], 'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': 'Written language', 'verbose_name_plural': 'Written languages'},
        ),
        migrations.AlterModelOptions(
            name='morphologydefinition',
            options={'verbose_name': 'Morphology definition', 'verbose_name_plural': 'Morphology definitions'},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'ordering': ['source'], 'verbose_name': 'Relation', 'verbose_name_plural': 'Relations'},
        ),
        migrations.AlterModelOptions(
            name='relationtoforeignsign',
            options={'ordering': ['gloss', 'loan', 'other_lang', 'other_lang_gloss'], 'verbose_name': 'Relation to Foreign Sign', 'verbose_name_plural': 'Relations to Foreign Signs'},
        ),
        migrations.AlterModelOptions(
            name='signlanguage',
            options={'ordering': ['name'], 'verbose_name': 'Sign language', 'verbose_name_plural': 'Sign languages'},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['gloss', 'index'], 'verbose_name': 'Translation equivalent', 'verbose_name_plural': 'Translation equivalents'},
        ),
    ]
