# Generated by Django 3.2.13 on 2022-06-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0034_merge_20220623_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='wordclasses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'field': 'wordclass'}, related_name='wordclass_glosses', to='dictionary.FieldChoice', verbose_name='Wordclasses'),
        ),
    ]
