# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0035_remove_gloss_url_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='gloss',
        ),
        migrations.AlterModelOptions(
            name='gloss',
            options={'ordering': ['idgloss'], 'permissions': (('update_video', 'Can Update Video'), ('search_gloss', 'Can Search/View Full Gloss Details'), ('export_csv', 'Can export sign details as CSV'), ('import_csv', 'Can import glosses from a CSV file'), ('view_advanced_properties', 'Include all properties in sign detail view'), ('publish_gloss', 'Can publish and unpublish Glosses')), 'verbose_name': 'Gloss', 'verbose_name_plural': 'Glosses'},
        ),
        migrations.RemoveField(
            model_name='gloss',
            name='is_proposed_new_sign',
        ),
        migrations.DeleteModel(
            name='Definition',
        ),
    ]
