# Generated by Django 3.2.13 on 2022-06-29 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0035_alter_gloss_wordclasses'),
        ('dictionary', '0035_auto_20220628_1355'),
    ]

    operations = [
    ]
