# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0036_auto_20170927_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gloss',
            name='in_web_dictionary',
        ),
    ]
