# Generated by Django 3.2.13 on 2022-06-30 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0036_merge_20220630_1040'),
        ('dictionary', '0036_merge_20220630_1053'),
    ]

    operations = [
    ]
