# Generated by Django 3.2.13 on 2022-06-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0036_merge_20220630_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='alternating_movement',
            field=models.BooleanField(default=False, null=True, verbose_name='Alternating Movement'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='repeated_movement',
            field=models.BooleanField(default=False, null=True, verbose_name='Repeated Movement'),
        ),
    ]
