# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0037_remove_gloss_in_web_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='signlanguage',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='signlanguage',
            name='name_fi',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
