# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 14:57
# Modified by Henri @ 2018-03-26: Added AlterField.
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0038_auto_20171017_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['gloss', 'order'], 'verbose_name': 'Translation equivalent', 'verbose_name_plural': 'Translation equivalents'},
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='index',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='translation',
            name='order',
            field=models.IntegerField(verbose_name='Order'),
        ),
    ]
