# Generated by Django 3.2.13 on 2022-07-04 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0037_auto_20220701_1106'),
        ('dictionary', '0038_merge_20220630_1613'),
    ]

    operations = [
    ]
