# Generated by Django 3.2.16 on 2023-12-11 22:48

from django.db import migrations
from django.conf import settings


def get_or_create_tags(apps, schema_validation):
    TagModel = apps.get_model("tagging", "Tag")
    tag_names = [
        settings.TAG_READY_FOR_VALIDATION,
        settings.TAG_VALIDATION_CHECK_RESULTS,
        settings.TAG_VALIDATION_PASS,
        settings.TAG_VALIDATION_FAIL,
        settings.TAG_VALIDATION_HOLD
    ]
    for name in tag_names:
        TagModel.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0040_auto_20220713_1713'),
        ('tagging', '0003_adapt_max_tag_length'),
    ]

    operations = [
        migrations.RunPython(get_or_create_tags, reverse_code=migrations.RunPython.noop)
    ]
