# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0042_auto_20180605_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='copyright',
            field=models.TextField(blank=True, verbose_name='Copyright'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Is this dataset is public or private?', verbose_name='Is public'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='public_name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Public name'),
        ),
    ]
