# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0043_auto_20180605_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='copyright_en',
            field=models.TextField(null=True, verbose_name='Copyright'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='copyright_fi',
            field=models.TextField(null=True, verbose_name='Copyright'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='description_fi',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='public_name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Public name'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='public_name_fi',
            field=models.CharField(max_length=60, null=True, verbose_name='Public name'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='copyright',
            field=models.TextField(verbose_name='Copyright'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='public_name',
            field=models.CharField(max_length=60, verbose_name='Public name'),
        ),
    ]
