# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-08 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0045_dataset_admins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['id'], 'permissions': (('view_dataset', 'View dataset'),), 'verbose_name': 'Lexicon', 'verbose_name_plural': 'Lexicons'},
        ),
    ]
