# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 11:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0046_auto_20180608_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='exclude_from_ecv',
            field=models.BooleanField(default=False, help_text='Exclude from ELAN externally controlled vocabularies (ECV)', verbose_name='Exclude from ECV'),
        ),
        migrations.AlterField(
            model_name='allowedtags',
            name='allowed_tags',
            field=models.ManyToManyField(to='tagging.Tag', verbose_name='Allowed tags'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Admins'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='signlanguage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.SignLanguage', verbose_name='Sign language'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='translation_languages',
            field=models.ManyToManyField(help_text='These languages are options for translation equivalents.', to='dictionary.Language', verbose_name='Translation equivalent languages'),
        ),
        migrations.AlterField(
            model_name='dialect',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.SignLanguage', verbose_name='Sign language'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='published',
            field=models.BooleanField(default=False, help_text='Publish this gloss in the public gloss list', verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='glosstranslations',
            name='gloss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Gloss', verbose_name='Gloss'),
        ),
        migrations.AlterField(
            model_name='glosstranslations',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='glossurl',
            name='gloss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Gloss', verbose_name='Gloss'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='gloss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Gloss', verbose_name='Gloss'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Keyword', verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Language', verbose_name='Language'),
        ),
    ]
