# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 15:40
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.contenttypes.models import ContentType


class Migration(migrations.Migration):

    def delete_contenttypes(app_label, schema_editor):
        # Deletes the contenttypes obsolete after this migration.
        try:
            ContentType.objects.get(app_label="feedback", model="generalfeedback").delete()
        except ContentType.DoesNotExist:
            pass
        try:
            ContentType.objects.get(app_label="feedback", model="interpreterfeedback").delete()
        except ContentType.DoesNotExist:
            pass
        try:
            ContentType.objects.get(app_label="feedback", model="missingsignfeedback").delete()
        except ContentType.DoesNotExist:
            pass
        try:
            ContentType.objects.get(app_label="feedback", model="signfeedback").delete()
        except ContentType.DoesNotExist:
            pass

    dependencies = [
        ('feedback', '0004_remove_signfeedback_translation_english'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalfeedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='interpreterfeedback',
            name='gloss',
        ),
        migrations.RemoveField(
            model_name='interpreterfeedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='missingsignfeedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='signfeedback',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='signfeedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='GeneralFeedback',
        ),
        migrations.DeleteModel(
            name='InterpreterFeedback',
        ),
        migrations.DeleteModel(
            name='MissingSignFeedback',
        ),
        migrations.DeleteModel(
            name='SignFeedback',
        ),
        migrations.RunPython(delete_contenttypes),
    ]
